datadog:
  apiKeyExistingSecret: datadog-secret
  site: datadoghq.eu
  tags:
    - "project:primary-markets"
    - "env:prod"
  logs:
    enabled: true
    containerCollectAll: true
  apm:
    enabled: true
clusterAgent:
  enabled: true
agents:
  enabled: true
